#ifndef APP_CONFIG_H
#define APP_CONFIG_H

typedef enum
{
  APP_MODE_PROJECT = 0,
  APP_MODE_RESET_HEARTBEAT_TEST = 1,
  APP_MODE_DISPLAY_EXPERIMENT = 2,
  APP_MODE_BITBANG_SPI_COLOR_TEST = 3,
  APP_MODE_HARDWARE_SPI_COLOR_TEST = 4,
  APP_MODE_WEATHER = 5
} AppMode;

#endif /* APP_CONFIG_H */
